[package]
name = "cloth_sim"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu-bootstrap = { git = "https://github.com/qlurkin/wgpu-bootstrap", tag = "v0.4.2" }
bytemuck = { version = "1.18", features = ["derive"] }
